spring:
  application:
    name: API_Gateway_Ravneet

  cloud:
    gateway:
      routes:
        - id: SPRINGAPIRAVNEET
          uri: lb://SPRINGAPIRAVNEET
          predicates:
            - Path=/hospital/**
        - id: HOSPITALMICROSERVICERAVNEET
          uri: lb://HOSPITALMICROSERVICERAVNEET
          predicates:
            - Path=/hospitalService/**

server:
  port: 8765


eureka:
  service-url: http://localhost:8761/eureka/
  client:
    register-with-eureka: true
